services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker --version

jobs:
  include:
    - stage: lint
      script: ./batect run lint

    - stage: unit test
      script: ./batect run unitTest

    - stage: integration test
      script: ./batect run integrationTest

    - stage: journey test
      script: ./batect run journeyTest

cache:
  directories:
    - .bundle-cache
